version: '3.8'
 
services:

  database:
    image: mysql
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: todo
    ports:
      - "6033:3306"
    volumes:
      - './cache:/var/lib/mysql'
  
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    links:
      - database
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
    depends_on:
      - database
    ports:
      - "8081:80"